### ISSUE TITLE
Custom Recipe Replacement

### ISSUE THREAD

**Issue by SmokeyTheBandicoot** [asiekierka/TinkeredHegemony#12]
I'm developing a personal modpack and I want to completely disable vanilla tools and armor. I use the recipe replacement but that only allows me to replace vanilla tools/weapons with tinkers construct tools/weapons. 
Would it be possible to actually specify another item as replacement? for example in every occurrence of minecraft:iron_pickaxe I'd like to replace it with another arbitrary registry name, for example minecraft:iron_ingot.

**Comment by asiekierka** [comment]
The mod is designed solely for replacing vanilla tools/weapons with Tinker's Construct tools/weapons. What is your use case?

**Comment by SmokeyTheBandicoot** [comment]
Large scale automation. Automating the crafting of machines which have vanilla tools in their recipe is really easy, while automating tinker tools is much harder because it involves automating a huge smeltery with a large amount of faucets (one for each tool part to automate by the number of materials). 
And even after that, I have no way to automate the building of a tool in the tool station/forge AFAIK.

My pack is strongly oriented towards automation and non-redundancy. The reason I installed TH was to remove the vanilla tool system and replace it with tinkers completely. That works amazingly for player tools, but not for recipe automation.

I could solve this problem by removing tools from recipes. I started doing this recipe-by-recipe but it is very tedious and time consuming, and if I want to rebalance the pack by making recipes harder (for example I want to change the substitute of the "<material> pickaxe" from "<material> ingot" to "<material> gear", I would have to rewrite 180+ recipes again.

**Comment by SmokeyTheBandicoot** [comment]
any news on this?

**Comment by YaibaToKen** [comment]
> I could solve this problem by removing tools from recipes. I started doing this recipe-by-recipe but it is very tedious and time consuming, and if I want to rebalance the pack by making recipes harder (for example I want to change the substitute of the "[material] pickaxe" from "[material] ingot" to "[material] gear", I would have to rewrite 180+ recipes again.

Easily solved by declaring a variable at the top of your ZS file, set it to whatever item you wish to use in the recipes and then reference the variable in your recipes instead of declaring the item directly in every recipe you change.

**Comment by SmokeyTheBandicoot** [comment]
Sure, bit I still have to look for all recipes with tools through JEI and edit them one by one. CraftTweaker seems to have a functionality for item replacement in all recipes, but I tried so many times and for some reasons I can't get it to work with TinkersContruct tools. For me, the issue still remains.
